// DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/J10.yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/J13.yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/J14.yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/J15.yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/J16.yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/J18.yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/J19.yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/J2.yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/J20.yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/J21.yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/J3.yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/J4.yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/J5.yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/J8.yaml
#pragma once

#define PIN_J10_6_switch_inputs MM100_IN_VSS
#define PIN_J10_6_event_inputs MM100_IN_VSS
#define PIN_J14_1 MM100_IGN4
#define PIN_J14_2 MM100_IGN5
#define PIN_J14_3 MM100_IGN6
#define PIN_J14_4 MM100_INJ4
#define PIN_J14_5 MM100_INJ5
#define PIN_J14_6 MM100_INJ6
#define PIN_J15_2 MM100_IN_VBATT
#define PIN_J15_5 MM100_OUT_PWM1
#define PIN_J15_6 MM100_OUT_PWM2
#define PIN_J15_7 MM100_INJ7
#define PIN_J15_8 MM100_INJ8
#define PIN_J16_1 MM100_IN_IAT_ANALOG
#define PIN_J16_3 MM100_IN_D2
#define PIN_J16_7 MM100_LED4_YELLOW
#define PIN_J18_2 MM100_UART8_TX
#define PIN_J18_4_event_inputs MM100_IN_D3
#define PIN_J18_4_sent_inputs MM100_IN_D3
#define PIN_J18_7 MM100_USB1ID
#define PIN_J2_1 MM100_IN_PPS_ANALOG
#define PIN_J2_2 MM100_IN_AUX2_ANALOG
#define PIN_J2_7 MM100_IN_CRANK
#define PIN_J2_8 MM100_IN_CAM
#define PIN_J20_1 MM100_SPI3_MOSI
#define PIN_J20_2 MM100_IN_D4
#define PIN_J21_3_switch_inputs MM100_IN_AUX3
#define PIN_J21_3_analog_inputs MM100_IN_AUX3_ANALOG
#define PIN_J21_6 MM100_IN_MAP1_ANALOG
#define PIN_J3_2 MM100_UART8_RX
#define PIN_J3_4 MM100_IN_D1
#define PIN_J3_7 MM100_IGN7
#define PIN_J4_3 MM100_IN_TPS_ANALOG
#define PIN_J4_4 MM100_IN_AUX1_ANALOG
#define PIN_J4_7 MM100_IN_CLT_ANALOG
#define PIN_J5_1 MM100_IGN1
#define PIN_J5_2 MM100_IGN2
#define PIN_J5_3 MM100_IGN3
#define PIN_J5_4 MM100_INJ1
#define PIN_J5_5 MM100_INJ2
#define PIN_J5_6 MM100_INJ3
#define PIN_J8_1 MM100_IGN8
#define PIN_J8_2 MM100_IN_O2S_ANALOG
