// DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/J10.yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/J13.yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/J14.yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/J15.yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/J16.yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/J18.yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/J19.yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/J2.yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/J20.yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/J21.yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/J3.yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/J4.yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/J5.yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/J8.yaml
#pragma once

Gpio GENERATED_OUTPUTS[] = {
	Gpio::MM100_INJ4, // J14-4 Injector 4
	Gpio::MM100_INJ5, // J14-5 Injector 5
	Gpio::MM100_INJ6, // J14-6 Injector 6
	Gpio::MM100_OUT_PWM1, // J15-5 Low Side 9
	Gpio::MM100_OUT_PWM2, // J15-6 Low Side 10
	Gpio::MM100_INJ7, // J15-7 Low Side 1
	Gpio::MM100_INJ8, // J15-8 Low Side 2
	Gpio::MM100_LED4_YELLOW, // J16-7 Low Side 8
	Gpio::MM100_USB1ID, // J18-7 Low Side 5
	Gpio::MM100_SPI3_MOSI, // J20-1 Low Side 6
	Gpio::MM100_IGN7, // J3-7 Low Side 3
	Gpio::MM100_INJ1, // J5-4 Injector 1
	Gpio::MM100_INJ2, // J5-5 Injector 2
	Gpio::MM100_INJ3, // J5-6 Injector 3
	Gpio::MM100_IGN8, // J8-1 Low Side 4
	Gpio::MM100_IGN4, // J14-1 Coil 4
	Gpio::MM100_IGN5, // J14-2 Coil 5
	Gpio::MM100_IGN6, // J14-3 Coil 6
	Gpio::MM100_IGN1, // J5-1 Coil 1
	Gpio::MM100_IGN2, // J5-2 Coil 2
	Gpio::MM100_IGN3, // J5-3 Coil 3
// "J14-4 Injector 4",
// "J14-5 Injector 5",
// "J14-6 Injector 6",
// "J15-5 Low Side 9",
// "J15-6 Low Side 10",
// "J15-7 Low Side 1",
// "J15-8 Low Side 2",
// "J16-7 Low Side 8",
// "J18-7 Low Side 5",
// "J20-1 Low Side 6",
// "J3-7 Low Side 3",
// "J5-4 Injector 1",
// "J5-5 Injector 2",
// "J5-6 Injector 3",
// "J8-1 Low Side 4",
// "J14-1 Coil 4",
// "J14-2 Coil 5",
// "J14-3 Coil 6",
// "J5-1 Coil 1",
// "J5-2 Coil 2",
// "J5-3 Coil 3",
}
