// DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/J10.yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/J13.yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/J14.yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/J15.yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/J16.yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/J18.yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/J19.yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/J2.yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/J20.yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/J21.yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/J3.yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/J4.yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/J5.yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/J8.yaml
#include "pch.h"

// see comments at declaration in pin_repository.h
const char* getBoardSpecificPinName(brain_pin_e brainPin) {
	switch (brainPin) {
		case Gpio::A10:
			return "J18-7 Low Side 5";
		case Gpio::A6:
			return "J2-8 Button 2";
		case Gpio::A7:
			return "J21-3 AIN2 / Digital input";
		case Gpio::A8:
			return "J14-6 Injector 6";
		case Gpio::A9:
			return "J5-5 Injector 2";
		case Gpio::B1:
			return "J2-7 Button 1";
		case Gpio::B8:
			return "J14-3 Coil 6";
		case Gpio::B9:
			return "J3-7 Low Side 3";
		case Gpio::C12:
			return "J20-1 Low Side 6";
		case Gpio::C13:
			return "J5-1 Coil 1";
		case Gpio::C6:
			return "J15-6 Low Side 10";
		case Gpio::D10:
			return "J14-4 Injector 4";
		case Gpio::D11:
			return "J5-6 Injector 3";
		case Gpio::D12:
			return "J15-8 Low Side 2";
		case Gpio::D13:
			return "J15-5 Low Side 9";
		case Gpio::D15:
			return "J15-7 Low Side 1";
		case Gpio::D2:
			return "J14-5 Injector 5";
		case Gpio::D3:
			return "J5-4 Injector 1";
		case Gpio::E0:
			return "VR_DISCRETE+";
		case Gpio::E1:
			return "VR_9924+";
		case Gpio::E11:
			return "J10-6 Flex / VSS";
		case Gpio::E12:
			return "J3-4 HALL1";
		case Gpio::E13:
			return "J16-3 HALL2";
		case Gpio::E14:
			return "J18-4 HALL3";
		case Gpio::E15:
			return "J20-2 Button 3";
		case Gpio::E2:
			return "J14-2 Coil 5";
		case Gpio::E3:
			return "J14-1 Coil 4";
		case Gpio::E4:
			return "J5-3 Coil 3";
		case Gpio::E5:
			return "J5-2 Coil 2";
		case Gpio::E6:
			return "J8-1 Low Side 4";
		case Gpio::E8:
			return "J16-7 Low Side 8";
		default:
			return nullptr;
	}
	return nullptr;
}
